version: "2"
services:
  redis-server:
    image: "redis"
    ports:
      - 6379:6379

  python-server:
    image: "thswpvm/pet-meeting-ml"
    ports:
      - 5000:5000

  server:
    image: "thswpvm/pet-meeting-server"
    depends_on:
      - redis-server
      - python-server
    ports:
      - 4000:4000
